services:
  db:
    image: postgis/postgis:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: samiaS
      POSTGRES_PASSWORD: samia1234
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-postgis.sh:/docker-entrypoint-initdb.d/init-postgis.sh
    networks:
      - app_network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=samiaS
      - POSTGRES_PASSWORD=samia1234
      - POSTGRES_DB=mydatabase
    networks:
      - app_network

  
volumes:
  postgres_data:
  pgadmin_data:

networks:
  app_network:
    driver: bridge