# Generated by Django 5.1.3 on 2024-12-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='country_code',
            field=models.CharField(max_length=20),
        ),
    ]
