# Generated by Django 5.1.3 on 2024-12-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_accommodation_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='interfaces/media/'),
        ),
    ]
