# Generated by Django 5.1.3 on 2024-12-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_accommodation_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
